
package com.amx.co.service.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.claro.WSSerGeneral.util.configuracion.Constantes;
import com.claro.WSSerGeneral.util.configuracion.Propiedades;
import com.claro.WSSerGeneral.util.configuracion.UtilsConstantes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "EnviarNotificacionMail", targetNamespace = "http://172.24.160.134:8084/EnviarNotificacionMailService-web/EnviarNotificacionMail?wsdl")
@WebServiceClient(name = "EnviarNotificacionMail", targetNamespace = "http://172.24.42.238:8002/EnviarNotificacionMailService-web/EnviarNotificacionMail?wsdl")

public class EnviarNotificacionMail
    extends Service
{

    private final static URL ENVIARNOTIFICACIONMAIL_WSDL_LOCATION;
    private final static WebServiceException ENVIARNOTIFICACIONMAIL_EXCEPTION;
    private final static QName ENVIARNOTIFICACIONMAIL_QNAME = new QName("http://www.amx.com/co/service/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", "EnviarNotificacionMail");
    private static Propiedades prop = Propiedades.getInstance();
    private static Logger logger = LogManager.getLogger(UtilsConstantes.LOGGER_PRINCIPAL);
    static {
        URL url = null;
        WebServiceException e = null;
        try {
           // url = new URL("http://172.24.160.134:8084/EnviarNotificacionMailService-web/EnviarNotificacionMail?wsdl");
        	String endPoint = prop.getPropiedad(Constantes.END_POINT_ENVIO_CORREO);
            logger.info("End point envio de correo: dos"+ endPoint );
            System.out.println("End point envio de correo dos: "+ endPoint);
            url = new URL(endPoint); 
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIARNOTIFICACIONMAIL_WSDL_LOCATION = url;
        ENVIARNOTIFICACIONMAIL_EXCEPTION = e;
    }

    public EnviarNotificacionMail() {
        super(__getWsdlLocation(), ENVIARNOTIFICACIONMAIL_QNAME);
    }

    public EnviarNotificacionMail(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENVIARNOTIFICACIONMAIL_QNAME, features);
    }

    public EnviarNotificacionMail(URL wsdlLocation) {
        super(wsdlLocation, ENVIARNOTIFICACIONMAIL_QNAME);
    }

    public EnviarNotificacionMail(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIARNOTIFICACIONMAIL_QNAME, features);
    }

    public EnviarNotificacionMail(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviarNotificacionMail(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnviarNotificacionMailInterface
     */
    @WebEndpoint(name = "EnviarNotificacionMailSOAPPort")
    public EnviarNotificacionMailInterface getEnviarNotificacionMailSOAPPort() {
        return super.getPort(new QName("http://www.amx.com/co/service/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", "EnviarNotificacionMailSOAPPort"), EnviarNotificacionMailInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviarNotificacionMailInterface
     */
    @WebEndpoint(name = "EnviarNotificacionMailSOAPPort")
    public EnviarNotificacionMailInterface getEnviarNotificacionMailSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.amx.com/co/service/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", "EnviarNotificacionMailSOAPPort"), EnviarNotificacionMailInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENVIARNOTIFICACIONMAIL_EXCEPTION!= null) {
            throw ENVIARNOTIFICACIONMAIL_EXCEPTION;
        }
        return ENVIARNOTIFICACIONMAIL_WSDL_LOCATION;
    }

}
