
package com.amx.co.service.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.EnviarMailRequest;
import com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.EnviarMailResponse;
import com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.ResetPropiedadesRequest;
import com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.ResetPropiedadesResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnviarNotificacionMailInterface", targetNamespace = "http://www.amx.com/co/service/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.amx.co.schema.mobile.common.aplicationintegration.comunes.v1.ObjectFactory.class,
    com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.ObjectFactory.class
})
public interface EnviarNotificacionMailInterface {


    /**
     * 
     * @param enviarMailRequest
     * @return
     *     returns com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.EnviarMailResponse
     * @throws Fault
     */
    @WebMethod(operationName = "EnviarMail", action = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0/EnviarMail")
    @WebResult(name = "EnviarMailResponse", targetNamespace = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", partName = "EnviarMailResponse")
    public EnviarMailResponse enviarMail(
        @WebParam(name = "EnviarMailRequest", targetNamespace = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", partName = "EnviarMailRequest")
        EnviarMailRequest enviarMailRequest)
        throws Fault
    ;

    /**
     * 
     * @param resetPropiedadesRequest
     * @return
     *     returns com.amx.co.schema.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1.ResetPropiedadesResponse
     * @throws Fault
     */
    @WebMethod(operationName = "ResetPropiedades", action = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0/ResetPropiedades")
    @WebResult(name = "ResetPropiedadesResponse", targetNamespace = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", partName = "ResetPropiedadesResponse")
    public ResetPropiedadesResponse resetPropiedades(
        @WebParam(name = "ResetPropiedadesRequest", targetNamespace = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0", partName = "ResetPropiedadesRequest")
        ResetPropiedadesRequest resetPropiedadesRequest)
        throws Fault
    ;

}
