
package com.amx.co.service.mobile.enterprise.aplicationintegration.enviarnotificacionmail.v1;

import javax.xml.ws.WebFault;
import com.amx.co.schema.mobile.common.aplicationintegration.comunes.v1.FaultMessageType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "faultMessage", targetNamespace = "http://www.amx.com/co/schema/mobile/enterprise/aplicationIntegration/EnviarNotificacionMail/v1.0")
public class Fault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultMessageType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, FaultMessageType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, FaultMessageType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.amx.co.schema.mobile.common.aplicationintegration.comunes.v1.FaultMessageType
     */
    public FaultMessageType getFaultInfo() {
        return faultInfo;
    }

}
